services:
  headscale:
    container_name: headscale
    image: headscale/headscale:0.22.3
    volumes:
      - ./config:/etc/headscale/
      - headscale:/var/lib/headscale
    command: headscale serve
    restart: unless-stopped
    network_mode: "host"


volumes:
  headscale:
    external: true
