services:
  headscale:
    container_name: headscale
    image: headscale/headscale:0.22.3
    volumes:
      - ./config:/etc/headscale/
      - headscale:/var/lib/headscale
    # ports:
    #   - "27896:8080"
    command: headscale serve
    restart: unless-stopped
    networks:
      cloudefire-network:
        ipv4_address: 10.10.0.2

volumes:
  headscale:
    external: true

networks:
  cloudefire-network:
    external: true