services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/etc/headscale
      - headscale:/var/lib/headscale
    command: ["headscale", "serve"]

volumes:
  headscale:
    external: true