server_url: http://vpn.example.com:8080
listen_addr: 0.0.0.0:8080

private_key_path: /var/lib/headscale/private.key

db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite

derp:
  auto_update: true

log:
  level: info
